/**
 *
 *  Inventory.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Inventory.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::testdb;

const std::string Inventory::Cols::_product_id = "product_id";
const std::string Inventory::Cols::_inventory_quantity = "inventory_quantity";
const std::string Inventory::Cols::_version = "version";
const std::string Inventory::primaryKeyName = "product_id";
const bool Inventory::hasPrimaryKey = true;
const std::string Inventory::tableName = "inventory";

const std::vector<typename Inventory::MetaData> Inventory::metaData_={
{"product_id","int32_t","int",4,0,1,1},
{"inventory_quantity","int32_t","int",4,0,0,1},
{"version","int32_t","int",4,0,0,1}
};
const std::string &Inventory::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Inventory::Inventory(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["product_id"].isNull())
        {
            productId_=std::make_shared<int32_t>(r["product_id"].as<int32_t>());
        }
        if(!r["inventory_quantity"].isNull())
        {
            inventoryQuantity_=std::make_shared<int32_t>(r["inventory_quantity"].as<int32_t>());
        }
        if(!r["version"].isNull())
        {
            version_=std::make_shared<int32_t>(r["version"].as<int32_t>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 3 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            productId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            inventoryQuantity_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            version_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
    }

}

Inventory::Inventory(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            productId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            inventoryQuantity_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            version_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
}

Inventory::Inventory(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("product_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["product_id"].isNull())
        {
            productId_=std::make_shared<int32_t>((int32_t)pJson["product_id"].asInt64());
        }
    }
    if(pJson.isMember("inventory_quantity"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["inventory_quantity"].isNull())
        {
            inventoryQuantity_=std::make_shared<int32_t>((int32_t)pJson["inventory_quantity"].asInt64());
        }
    }
    if(pJson.isMember("version"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["version"].isNull())
        {
            version_=std::make_shared<int32_t>((int32_t)pJson["version"].asInt64());
        }
    }
}

void Inventory::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            productId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            inventoryQuantity_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            version_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
}

void Inventory::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("product_id"))
    {
        if(!pJson["product_id"].isNull())
        {
            productId_=std::make_shared<int32_t>((int32_t)pJson["product_id"].asInt64());
        }
    }
    if(pJson.isMember("inventory_quantity"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["inventory_quantity"].isNull())
        {
            inventoryQuantity_=std::make_shared<int32_t>((int32_t)pJson["inventory_quantity"].asInt64());
        }
    }
    if(pJson.isMember("version"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["version"].isNull())
        {
            version_=std::make_shared<int32_t>((int32_t)pJson["version"].asInt64());
        }
    }
}

const int32_t &Inventory::getValueOfProductId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(productId_)
        return *productId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Inventory::getProductId() const noexcept
{
    return productId_;
}
void Inventory::setProductId(const int32_t &pProductId) noexcept
{
    productId_ = std::make_shared<int32_t>(pProductId);
    dirtyFlag_[0] = true;
}
const typename Inventory::PrimaryKeyType & Inventory::getPrimaryKey() const
{
    assert(productId_);
    return *productId_;
}

const int32_t &Inventory::getValueOfInventoryQuantity() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(inventoryQuantity_)
        return *inventoryQuantity_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Inventory::getInventoryQuantity() const noexcept
{
    return inventoryQuantity_;
}
void Inventory::setInventoryQuantity(const int32_t &pInventoryQuantity) noexcept
{
    inventoryQuantity_ = std::make_shared<int32_t>(pInventoryQuantity);
    dirtyFlag_[1] = true;
}

const int32_t &Inventory::getValueOfVersion() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(version_)
        return *version_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Inventory::getVersion() const noexcept
{
    return version_;
}
void Inventory::setVersion(const int32_t &pVersion) noexcept
{
    version_ = std::make_shared<int32_t>(pVersion);
    dirtyFlag_[2] = true;
}

void Inventory::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Inventory::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "product_id",
        "inventory_quantity",
        "version"
    };
    return inCols;
}

void Inventory::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getProductId())
        {
            binder << getValueOfProductId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getInventoryQuantity())
        {
            binder << getValueOfInventoryQuantity();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getVersion())
        {
            binder << getValueOfVersion();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Inventory::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    return ret;
}

void Inventory::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getProductId())
        {
            binder << getValueOfProductId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getInventoryQuantity())
        {
            binder << getValueOfInventoryQuantity();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getVersion())
        {
            binder << getValueOfVersion();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Inventory::toJson() const
{
    Json::Value ret;
    if(getProductId())
    {
        ret["product_id"]=getValueOfProductId();
    }
    else
    {
        ret["product_id"]=Json::Value();
    }
    if(getInventoryQuantity())
    {
        ret["inventory_quantity"]=getValueOfInventoryQuantity();
    }
    else
    {
        ret["inventory_quantity"]=Json::Value();
    }
    if(getVersion())
    {
        ret["version"]=getValueOfVersion();
    }
    else
    {
        ret["version"]=Json::Value();
    }
    return ret;
}

std::string Inventory::toString() const
{
    return toJson().toStyledString();
}

Json::Value Inventory::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 3)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getProductId())
            {
                ret[pMasqueradingVector[0]]=getValueOfProductId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getInventoryQuantity())
            {
                ret[pMasqueradingVector[1]]=getValueOfInventoryQuantity();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getVersion())
            {
                ret[pMasqueradingVector[2]]=getValueOfVersion();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getProductId())
    {
        ret["product_id"]=getValueOfProductId();
    }
    else
    {
        ret["product_id"]=Json::Value();
    }
    if(getInventoryQuantity())
    {
        ret["inventory_quantity"]=getValueOfInventoryQuantity();
    }
    else
    {
        ret["inventory_quantity"]=Json::Value();
    }
    if(getVersion())
    {
        ret["version"]=getValueOfVersion();
    }
    else
    {
        ret["version"]=Json::Value();
    }
    return ret;
}

bool Inventory::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("product_id"))
    {
        if(!validJsonOfField(0, "product_id", pJson["product_id"], err, true))
            return false;
    }
    else
    {
        err="The product_id column cannot be null";
        return false;
    }
    if(pJson.isMember("inventory_quantity"))
    {
        if(!validJsonOfField(1, "inventory_quantity", pJson["inventory_quantity"], err, true))
            return false;
    }
    else
    {
        err="The inventory_quantity column cannot be null";
        return false;
    }
    if(pJson.isMember("version"))
    {
        if(!validJsonOfField(2, "version", pJson["version"], err, true))
            return false;
    }
    else
    {
        err="The version column cannot be null";
        return false;
    }
    return true;
}
bool Inventory::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                   const std::vector<std::string> &pMasqueradingVector,
                                                   std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Inventory::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("product_id"))
    {
        if(!validJsonOfField(0, "product_id", pJson["product_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("inventory_quantity"))
    {
        if(!validJsonOfField(1, "inventory_quantity", pJson["inventory_quantity"], err, false))
            return false;
    }
    if(pJson.isMember("version"))
    {
        if(!validJsonOfField(2, "version", pJson["version"], err, false))
            return false;
    }
    return true;
}
bool Inventory::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                 const std::vector<std::string> &pMasqueradingVector,
                                                 std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Inventory::validJsonOfField(size_t index,
                                 const std::string &fieldName,
                                 const Json::Value &pJson,
                                 std::string &err,
                                 bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
