/**
 *
 *  OrderMainTable.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "OrderMainTable.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::testdb;

const std::string OrderMainTable::Cols::_order_main_table_id = "order_main_table_id";
const std::string OrderMainTable::Cols::_user_id = "user_id";
const std::string OrderMainTable::Cols::_order_number = "order_number";
const std::string OrderMainTable::Cols::_purchase_date = "purchase_date";
const std::string OrderMainTable::Cols::_total_order_amount = "total_order_amount";
const std::string OrderMainTable::primaryKeyName = "order_main_table_id";
const bool OrderMainTable::hasPrimaryKey = true;
const std::string OrderMainTable::tableName = "order_main_table";

const std::vector<typename OrderMainTable::MetaData> OrderMainTable::metaData_={
{"order_main_table_id","int32_t","int",4,0,1,1},
{"user_id","int32_t","int",4,0,0,1},
{"order_number","std::string","varchar(32)",32,0,0,1},
{"purchase_date","::trantor::Date","datetime",0,0,0,1},
{"total_order_amount","std::string","decimal(10,0)",0,0,0,1}
};
const std::string &OrderMainTable::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
OrderMainTable::OrderMainTable(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["order_main_table_id"].isNull())
        {
            orderMainTableId_=std::make_shared<int32_t>(r["order_main_table_id"].as<int32_t>());
        }
        if(!r["user_id"].isNull())
        {
            userId_=std::make_shared<int32_t>(r["user_id"].as<int32_t>());
        }
        if(!r["order_number"].isNull())
        {
            orderNumber_=std::make_shared<std::string>(r["order_number"].as<std::string>());
        }
        if(!r["purchase_date"].isNull())
        {
            auto timeStr = r["purchase_date"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                purchaseDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["total_order_amount"].isNull())
        {
            totalOrderAmount_=std::make_shared<std::string>(r["total_order_amount"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 5 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            orderMainTableId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            userId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            orderNumber_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                purchaseDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            totalOrderAmount_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

OrderMainTable::OrderMainTable(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 5)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            orderMainTableId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            userId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            orderNumber_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[3]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                purchaseDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            totalOrderAmount_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
}

OrderMainTable::OrderMainTable(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("order_main_table_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["order_main_table_id"].isNull())
        {
            orderMainTableId_=std::make_shared<int32_t>((int32_t)pJson["order_main_table_id"].asInt64());
        }
    }
    if(pJson.isMember("user_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<int32_t>((int32_t)pJson["user_id"].asInt64());
        }
    }
    if(pJson.isMember("order_number"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["order_number"].isNull())
        {
            orderNumber_=std::make_shared<std::string>(pJson["order_number"].asString());
        }
    }
    if(pJson.isMember("purchase_date"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["purchase_date"].isNull())
        {
            auto timeStr = pJson["purchase_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                purchaseDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("total_order_amount"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["total_order_amount"].isNull())
        {
            totalOrderAmount_=std::make_shared<std::string>(pJson["total_order_amount"].asString());
        }
    }
}

void OrderMainTable::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 5)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            orderMainTableId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            userId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            orderNumber_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[3]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                purchaseDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            totalOrderAmount_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
}

void OrderMainTable::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("order_main_table_id"))
    {
        if(!pJson["order_main_table_id"].isNull())
        {
            orderMainTableId_=std::make_shared<int32_t>((int32_t)pJson["order_main_table_id"].asInt64());
        }
    }
    if(pJson.isMember("user_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<int32_t>((int32_t)pJson["user_id"].asInt64());
        }
    }
    if(pJson.isMember("order_number"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["order_number"].isNull())
        {
            orderNumber_=std::make_shared<std::string>(pJson["order_number"].asString());
        }
    }
    if(pJson.isMember("purchase_date"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["purchase_date"].isNull())
        {
            auto timeStr = pJson["purchase_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                purchaseDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("total_order_amount"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["total_order_amount"].isNull())
        {
            totalOrderAmount_=std::make_shared<std::string>(pJson["total_order_amount"].asString());
        }
    }
}

const int32_t &OrderMainTable::getValueOfOrderMainTableId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(orderMainTableId_)
        return *orderMainTableId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &OrderMainTable::getOrderMainTableId() const noexcept
{
    return orderMainTableId_;
}
void OrderMainTable::setOrderMainTableId(const int32_t &pOrderMainTableId) noexcept
{
    orderMainTableId_ = std::make_shared<int32_t>(pOrderMainTableId);
    dirtyFlag_[0] = true;
}
const typename OrderMainTable::PrimaryKeyType & OrderMainTable::getPrimaryKey() const
{
    assert(orderMainTableId_);
    return *orderMainTableId_;
}

const int32_t &OrderMainTable::getValueOfUserId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(userId_)
        return *userId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &OrderMainTable::getUserId() const noexcept
{
    return userId_;
}
void OrderMainTable::setUserId(const int32_t &pUserId) noexcept
{
    userId_ = std::make_shared<int32_t>(pUserId);
    dirtyFlag_[1] = true;
}

const std::string &OrderMainTable::getValueOfOrderNumber() const noexcept
{
    static const std::string defaultValue = std::string();
    if(orderNumber_)
        return *orderNumber_;
    return defaultValue;
}
const std::shared_ptr<std::string> &OrderMainTable::getOrderNumber() const noexcept
{
    return orderNumber_;
}
void OrderMainTable::setOrderNumber(const std::string &pOrderNumber) noexcept
{
    orderNumber_ = std::make_shared<std::string>(pOrderNumber);
    dirtyFlag_[2] = true;
}
void OrderMainTable::setOrderNumber(std::string &&pOrderNumber) noexcept
{
    orderNumber_ = std::make_shared<std::string>(std::move(pOrderNumber));
    dirtyFlag_[2] = true;
}

const ::trantor::Date &OrderMainTable::getValueOfPurchaseDate() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(purchaseDate_)
        return *purchaseDate_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &OrderMainTable::getPurchaseDate() const noexcept
{
    return purchaseDate_;
}
void OrderMainTable::setPurchaseDate(const ::trantor::Date &pPurchaseDate) noexcept
{
    purchaseDate_ = std::make_shared<::trantor::Date>(pPurchaseDate);
    dirtyFlag_[3] = true;
}

const std::string &OrderMainTable::getValueOfTotalOrderAmount() const noexcept
{
    static const std::string defaultValue = std::string();
    if(totalOrderAmount_)
        return *totalOrderAmount_;
    return defaultValue;
}
const std::shared_ptr<std::string> &OrderMainTable::getTotalOrderAmount() const noexcept
{
    return totalOrderAmount_;
}
void OrderMainTable::setTotalOrderAmount(const std::string &pTotalOrderAmount) noexcept
{
    totalOrderAmount_ = std::make_shared<std::string>(pTotalOrderAmount);
    dirtyFlag_[4] = true;
}
void OrderMainTable::setTotalOrderAmount(std::string &&pTotalOrderAmount) noexcept
{
    totalOrderAmount_ = std::make_shared<std::string>(std::move(pTotalOrderAmount));
    dirtyFlag_[4] = true;
}

void OrderMainTable::updateId(const uint64_t id)
{
}

const std::vector<std::string> &OrderMainTable::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "order_main_table_id",
        "user_id",
        "order_number",
        "purchase_date",
        "total_order_amount"
    };
    return inCols;
}

void OrderMainTable::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getOrderMainTableId())
        {
            binder << getValueOfOrderMainTableId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getOrderNumber())
        {
            binder << getValueOfOrderNumber();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getPurchaseDate())
        {
            binder << getValueOfPurchaseDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getTotalOrderAmount())
        {
            binder << getValueOfTotalOrderAmount();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> OrderMainTable::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    return ret;
}

void OrderMainTable::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getOrderMainTableId())
        {
            binder << getValueOfOrderMainTableId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getOrderNumber())
        {
            binder << getValueOfOrderNumber();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getPurchaseDate())
        {
            binder << getValueOfPurchaseDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getTotalOrderAmount())
        {
            binder << getValueOfTotalOrderAmount();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value OrderMainTable::toJson() const
{
    Json::Value ret;
    if(getOrderMainTableId())
    {
        ret["order_main_table_id"]=getValueOfOrderMainTableId();
    }
    else
    {
        ret["order_main_table_id"]=Json::Value();
    }
    if(getUserId())
    {
        ret["user_id"]=getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getOrderNumber())
    {
        ret["order_number"]=getValueOfOrderNumber();
    }
    else
    {
        ret["order_number"]=Json::Value();
    }
    if(getPurchaseDate())
    {
        ret["purchase_date"]=getPurchaseDate()->toDbStringLocal();
    }
    else
    {
        ret["purchase_date"]=Json::Value();
    }
    if(getTotalOrderAmount())
    {
        ret["total_order_amount"]=getValueOfTotalOrderAmount();
    }
    else
    {
        ret["total_order_amount"]=Json::Value();
    }
    return ret;
}

std::string OrderMainTable::toString() const
{
    return toJson().toStyledString();
}

Json::Value OrderMainTable::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 5)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getOrderMainTableId())
            {
                ret[pMasqueradingVector[0]]=getValueOfOrderMainTableId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getUserId())
            {
                ret[pMasqueradingVector[1]]=getValueOfUserId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getOrderNumber())
            {
                ret[pMasqueradingVector[2]]=getValueOfOrderNumber();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getPurchaseDate())
            {
                ret[pMasqueradingVector[3]]=getPurchaseDate()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getTotalOrderAmount())
            {
                ret[pMasqueradingVector[4]]=getValueOfTotalOrderAmount();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getOrderMainTableId())
    {
        ret["order_main_table_id"]=getValueOfOrderMainTableId();
    }
    else
    {
        ret["order_main_table_id"]=Json::Value();
    }
    if(getUserId())
    {
        ret["user_id"]=getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getOrderNumber())
    {
        ret["order_number"]=getValueOfOrderNumber();
    }
    else
    {
        ret["order_number"]=Json::Value();
    }
    if(getPurchaseDate())
    {
        ret["purchase_date"]=getPurchaseDate()->toDbStringLocal();
    }
    else
    {
        ret["purchase_date"]=Json::Value();
    }
    if(getTotalOrderAmount())
    {
        ret["total_order_amount"]=getValueOfTotalOrderAmount();
    }
    else
    {
        ret["total_order_amount"]=Json::Value();
    }
    return ret;
}

bool OrderMainTable::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("order_main_table_id"))
    {
        if(!validJsonOfField(0, "order_main_table_id", pJson["order_main_table_id"], err, true))
            return false;
    }
    else
    {
        err="The order_main_table_id column cannot be null";
        return false;
    }
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(1, "user_id", pJson["user_id"], err, true))
            return false;
    }
    else
    {
        err="The user_id column cannot be null";
        return false;
    }
    if(pJson.isMember("order_number"))
    {
        if(!validJsonOfField(2, "order_number", pJson["order_number"], err, true))
            return false;
    }
    else
    {
        err="The order_number column cannot be null";
        return false;
    }
    if(pJson.isMember("purchase_date"))
    {
        if(!validJsonOfField(3, "purchase_date", pJson["purchase_date"], err, true))
            return false;
    }
    else
    {
        err="The purchase_date column cannot be null";
        return false;
    }
    if(pJson.isMember("total_order_amount"))
    {
        if(!validJsonOfField(4, "total_order_amount", pJson["total_order_amount"], err, true))
            return false;
    }
    else
    {
        err="The total_order_amount column cannot be null";
        return false;
    }
    return true;
}
bool OrderMainTable::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                        const std::vector<std::string> &pMasqueradingVector,
                                                        std::string &err)
{
    if(pMasqueradingVector.size() != 5)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool OrderMainTable::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("order_main_table_id"))
    {
        if(!validJsonOfField(0, "order_main_table_id", pJson["order_main_table_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(1, "user_id", pJson["user_id"], err, false))
            return false;
    }
    if(pJson.isMember("order_number"))
    {
        if(!validJsonOfField(2, "order_number", pJson["order_number"], err, false))
            return false;
    }
    if(pJson.isMember("purchase_date"))
    {
        if(!validJsonOfField(3, "purchase_date", pJson["purchase_date"], err, false))
            return false;
    }
    if(pJson.isMember("total_order_amount"))
    {
        if(!validJsonOfField(4, "total_order_amount", pJson["total_order_amount"], err, false))
            return false;
    }
    return true;
}
bool OrderMainTable::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                      const std::vector<std::string> &pMasqueradingVector,
                                                      std::string &err)
{
    if(pMasqueradingVector.size() != 5)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool OrderMainTable::validJsonOfField(size_t index,
                                      const std::string &fieldName,
                                      const Json::Value &pJson,
                                      std::string &err,
                                      bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 32)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 32)";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
