/**
 *
 *  OrderMainTable.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace testdb
{

class OrderMainTable
{
  public:
    struct Cols
    {
        static const std::string _order_main_table_id;
        static const std::string _user_id;
        static const std::string _order_number;
        static const std::string _purchase_date;
        static const std::string _total_order_amount;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = int32_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit OrderMainTable(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit OrderMainTable(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    OrderMainTable(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    OrderMainTable() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column order_main_table_id  */
    ///Get the value of the column order_main_table_id, returns the default value if the column is null
    const int32_t &getValueOfOrderMainTableId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getOrderMainTableId() const noexcept;
    ///Set the value of the column order_main_table_id
    void setOrderMainTableId(const int32_t &pOrderMainTableId) noexcept;

    /**  For column user_id  */
    ///Get the value of the column user_id, returns the default value if the column is null
    const int32_t &getValueOfUserId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getUserId() const noexcept;
    ///Set the value of the column user_id
    void setUserId(const int32_t &pUserId) noexcept;

    /**  For column order_number  */
    ///Get the value of the column order_number, returns the default value if the column is null
    const std::string &getValueOfOrderNumber() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getOrderNumber() const noexcept;
    ///Set the value of the column order_number
    void setOrderNumber(const std::string &pOrderNumber) noexcept;
    void setOrderNumber(std::string &&pOrderNumber) noexcept;

    /**  For column purchase_date  */
    ///Get the value of the column purchase_date, returns the default value if the column is null
    const ::trantor::Date &getValueOfPurchaseDate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getPurchaseDate() const noexcept;
    ///Set the value of the column purchase_date
    void setPurchaseDate(const ::trantor::Date &pPurchaseDate) noexcept;

    /**  For column total_order_amount  */
    ///Get the value of the column total_order_amount, returns the default value if the column is null
    const std::string &getValueOfTotalOrderAmount() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getTotalOrderAmount() const noexcept;
    ///Set the value of the column total_order_amount
    void setTotalOrderAmount(const std::string &pTotalOrderAmount) noexcept;
    void setTotalOrderAmount(std::string &&pTotalOrderAmount) noexcept;


    static size_t getColumnNumber() noexcept {  return 5;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<OrderMainTable>;
    friend drogon::orm::BaseBuilder<OrderMainTable, true, true>;
    friend drogon::orm::BaseBuilder<OrderMainTable, true, false>;
    friend drogon::orm::BaseBuilder<OrderMainTable, false, true>;
    friend drogon::orm::BaseBuilder<OrderMainTable, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<OrderMainTable>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int32_t> orderMainTableId_;
    std::shared_ptr<int32_t> userId_;
    std::shared_ptr<std::string> orderNumber_;
    std::shared_ptr<::trantor::Date> purchaseDate_;
    std::shared_ptr<std::string> totalOrderAmount_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[5]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where order_main_table_id = ?";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where order_main_table_id = ?";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
        if(dirtyFlag_[0])
        {
            sql += "order_main_table_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[1])
        {
            sql += "user_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "order_number,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "purchase_date,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "total_order_amount,";
            ++parametersCount;
        }
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        if(dirtyFlag_[0])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[1])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[2])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[3])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[4])
        {
            sql.append("?,");

        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        sql.append(1, ')');
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace testdb
} // namespace drogon_model
