/**
 *
 *  OrderDetailTable.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace testdb
{

class OrderDetailTable
{
  public:
    struct Cols
    {
        static const std::string _order_detail_table_id;
        static const std::string _order_main_table_id;
        static const std::string _product_id;
        static const std::string _quantity_purchased;
        static const std::string _price_at_purchase;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = int32_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit OrderDetailTable(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit OrderDetailTable(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    OrderDetailTable(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    OrderDetailTable() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column order_detail_table_id  */
    ///Get the value of the column order_detail_table_id, returns the default value if the column is null
    const int32_t &getValueOfOrderDetailTableId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getOrderDetailTableId() const noexcept;
    ///Set the value of the column order_detail_table_id
    void setOrderDetailTableId(const int32_t &pOrderDetailTableId) noexcept;

    /**  For column order_main_table_id  */
    ///Get the value of the column order_main_table_id, returns the default value if the column is null
    const int32_t &getValueOfOrderMainTableId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getOrderMainTableId() const noexcept;
    ///Set the value of the column order_main_table_id
    void setOrderMainTableId(const int32_t &pOrderMainTableId) noexcept;

    /**  For column product_id  */
    ///Get the value of the column product_id, returns the default value if the column is null
    const int32_t &getValueOfProductId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getProductId() const noexcept;
    ///Set the value of the column product_id
    void setProductId(const int32_t &pProductId) noexcept;

    /**  For column quantity_purchased  */
    ///Get the value of the column quantity_purchased, returns the default value if the column is null
    const int32_t &getValueOfQuantityPurchased() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getQuantityPurchased() const noexcept;
    ///Set the value of the column quantity_purchased
    void setQuantityPurchased(const int32_t &pQuantityPurchased) noexcept;

    /**  For column price_at_purchase  */
    ///Get the value of the column price_at_purchase, returns the default value if the column is null
    const std::string &getValueOfPriceAtPurchase() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getPriceAtPurchase() const noexcept;
    ///Set the value of the column price_at_purchase
    void setPriceAtPurchase(const std::string &pPriceAtPurchase) noexcept;
    void setPriceAtPurchase(std::string &&pPriceAtPurchase) noexcept;


    static size_t getColumnNumber() noexcept {  return 5;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<OrderDetailTable>;
    friend drogon::orm::BaseBuilder<OrderDetailTable, true, true>;
    friend drogon::orm::BaseBuilder<OrderDetailTable, true, false>;
    friend drogon::orm::BaseBuilder<OrderDetailTable, false, true>;
    friend drogon::orm::BaseBuilder<OrderDetailTable, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<OrderDetailTable>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int32_t> orderDetailTableId_;
    std::shared_ptr<int32_t> orderMainTableId_;
    std::shared_ptr<int32_t> productId_;
    std::shared_ptr<int32_t> quantityPurchased_;
    std::shared_ptr<std::string> priceAtPurchase_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[5]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where order_detail_table_id = ?";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where order_detail_table_id = ?";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
        if(dirtyFlag_[0])
        {
            sql += "order_detail_table_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[1])
        {
            sql += "order_main_table_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "product_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "quantity_purchased,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "price_at_purchase,";
            ++parametersCount;
        }
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        if(dirtyFlag_[0])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[1])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[2])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[3])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[4])
        {
            sql.append("?,");

        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        sql.append(1, ')');
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace testdb
} // namespace drogon_model
