/**
 *
 *  OrderDetailTable.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "OrderDetailTable.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::testdb;

const std::string OrderDetailTable::Cols::_order_detail_table_id = "order_detail_table_id";
const std::string OrderDetailTable::Cols::_order_main_table_id = "order_main_table_id";
const std::string OrderDetailTable::Cols::_product_id = "product_id";
const std::string OrderDetailTable::Cols::_quantity_purchased = "quantity_purchased";
const std::string OrderDetailTable::Cols::_price_at_purchase = "price_at_purchase";
const std::string OrderDetailTable::primaryKeyName = "order_detail_table_id";
const bool OrderDetailTable::hasPrimaryKey = true;
const std::string OrderDetailTable::tableName = "order_detail_table";

const std::vector<typename OrderDetailTable::MetaData> OrderDetailTable::metaData_={
{"order_detail_table_id","int32_t","int",4,0,1,1},
{"order_main_table_id","int32_t","int",4,0,0,1},
{"product_id","int32_t","int",4,0,0,1},
{"quantity_purchased","int32_t","int",4,0,0,1},
{"price_at_purchase","std::string","decimal(10,0)",0,0,0,1}
};
const std::string &OrderDetailTable::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
OrderDetailTable::OrderDetailTable(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["order_detail_table_id"].isNull())
        {
            orderDetailTableId_=std::make_shared<int32_t>(r["order_detail_table_id"].as<int32_t>());
        }
        if(!r["order_main_table_id"].isNull())
        {
            orderMainTableId_=std::make_shared<int32_t>(r["order_main_table_id"].as<int32_t>());
        }
        if(!r["product_id"].isNull())
        {
            productId_=std::make_shared<int32_t>(r["product_id"].as<int32_t>());
        }
        if(!r["quantity_purchased"].isNull())
        {
            quantityPurchased_=std::make_shared<int32_t>(r["quantity_purchased"].as<int32_t>());
        }
        if(!r["price_at_purchase"].isNull())
        {
            priceAtPurchase_=std::make_shared<std::string>(r["price_at_purchase"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 5 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            orderDetailTableId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            orderMainTableId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            productId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            quantityPurchased_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            priceAtPurchase_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

OrderDetailTable::OrderDetailTable(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 5)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            orderDetailTableId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            orderMainTableId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            productId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            quantityPurchased_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            priceAtPurchase_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
}

OrderDetailTable::OrderDetailTable(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("order_detail_table_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["order_detail_table_id"].isNull())
        {
            orderDetailTableId_=std::make_shared<int32_t>((int32_t)pJson["order_detail_table_id"].asInt64());
        }
    }
    if(pJson.isMember("order_main_table_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["order_main_table_id"].isNull())
        {
            orderMainTableId_=std::make_shared<int32_t>((int32_t)pJson["order_main_table_id"].asInt64());
        }
    }
    if(pJson.isMember("product_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["product_id"].isNull())
        {
            productId_=std::make_shared<int32_t>((int32_t)pJson["product_id"].asInt64());
        }
    }
    if(pJson.isMember("quantity_purchased"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["quantity_purchased"].isNull())
        {
            quantityPurchased_=std::make_shared<int32_t>((int32_t)pJson["quantity_purchased"].asInt64());
        }
    }
    if(pJson.isMember("price_at_purchase"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["price_at_purchase"].isNull())
        {
            priceAtPurchase_=std::make_shared<std::string>(pJson["price_at_purchase"].asString());
        }
    }
}

void OrderDetailTable::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 5)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            orderDetailTableId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            orderMainTableId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            productId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            quantityPurchased_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            priceAtPurchase_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
}

void OrderDetailTable::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("order_detail_table_id"))
    {
        if(!pJson["order_detail_table_id"].isNull())
        {
            orderDetailTableId_=std::make_shared<int32_t>((int32_t)pJson["order_detail_table_id"].asInt64());
        }
    }
    if(pJson.isMember("order_main_table_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["order_main_table_id"].isNull())
        {
            orderMainTableId_=std::make_shared<int32_t>((int32_t)pJson["order_main_table_id"].asInt64());
        }
    }
    if(pJson.isMember("product_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["product_id"].isNull())
        {
            productId_=std::make_shared<int32_t>((int32_t)pJson["product_id"].asInt64());
        }
    }
    if(pJson.isMember("quantity_purchased"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["quantity_purchased"].isNull())
        {
            quantityPurchased_=std::make_shared<int32_t>((int32_t)pJson["quantity_purchased"].asInt64());
        }
    }
    if(pJson.isMember("price_at_purchase"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["price_at_purchase"].isNull())
        {
            priceAtPurchase_=std::make_shared<std::string>(pJson["price_at_purchase"].asString());
        }
    }
}

const int32_t &OrderDetailTable::getValueOfOrderDetailTableId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(orderDetailTableId_)
        return *orderDetailTableId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &OrderDetailTable::getOrderDetailTableId() const noexcept
{
    return orderDetailTableId_;
}
void OrderDetailTable::setOrderDetailTableId(const int32_t &pOrderDetailTableId) noexcept
{
    orderDetailTableId_ = std::make_shared<int32_t>(pOrderDetailTableId);
    dirtyFlag_[0] = true;
}
const typename OrderDetailTable::PrimaryKeyType & OrderDetailTable::getPrimaryKey() const
{
    assert(orderDetailTableId_);
    return *orderDetailTableId_;
}

const int32_t &OrderDetailTable::getValueOfOrderMainTableId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(orderMainTableId_)
        return *orderMainTableId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &OrderDetailTable::getOrderMainTableId() const noexcept
{
    return orderMainTableId_;
}
void OrderDetailTable::setOrderMainTableId(const int32_t &pOrderMainTableId) noexcept
{
    orderMainTableId_ = std::make_shared<int32_t>(pOrderMainTableId);
    dirtyFlag_[1] = true;
}

const int32_t &OrderDetailTable::getValueOfProductId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(productId_)
        return *productId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &OrderDetailTable::getProductId() const noexcept
{
    return productId_;
}
void OrderDetailTable::setProductId(const int32_t &pProductId) noexcept
{
    productId_ = std::make_shared<int32_t>(pProductId);
    dirtyFlag_[2] = true;
}

const int32_t &OrderDetailTable::getValueOfQuantityPurchased() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(quantityPurchased_)
        return *quantityPurchased_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &OrderDetailTable::getQuantityPurchased() const noexcept
{
    return quantityPurchased_;
}
void OrderDetailTable::setQuantityPurchased(const int32_t &pQuantityPurchased) noexcept
{
    quantityPurchased_ = std::make_shared<int32_t>(pQuantityPurchased);
    dirtyFlag_[3] = true;
}

const std::string &OrderDetailTable::getValueOfPriceAtPurchase() const noexcept
{
    static const std::string defaultValue = std::string();
    if(priceAtPurchase_)
        return *priceAtPurchase_;
    return defaultValue;
}
const std::shared_ptr<std::string> &OrderDetailTable::getPriceAtPurchase() const noexcept
{
    return priceAtPurchase_;
}
void OrderDetailTable::setPriceAtPurchase(const std::string &pPriceAtPurchase) noexcept
{
    priceAtPurchase_ = std::make_shared<std::string>(pPriceAtPurchase);
    dirtyFlag_[4] = true;
}
void OrderDetailTable::setPriceAtPurchase(std::string &&pPriceAtPurchase) noexcept
{
    priceAtPurchase_ = std::make_shared<std::string>(std::move(pPriceAtPurchase));
    dirtyFlag_[4] = true;
}

void OrderDetailTable::updateId(const uint64_t id)
{
}

const std::vector<std::string> &OrderDetailTable::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "order_detail_table_id",
        "order_main_table_id",
        "product_id",
        "quantity_purchased",
        "price_at_purchase"
    };
    return inCols;
}

void OrderDetailTable::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getOrderDetailTableId())
        {
            binder << getValueOfOrderDetailTableId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getOrderMainTableId())
        {
            binder << getValueOfOrderMainTableId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getProductId())
        {
            binder << getValueOfProductId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getQuantityPurchased())
        {
            binder << getValueOfQuantityPurchased();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getPriceAtPurchase())
        {
            binder << getValueOfPriceAtPurchase();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> OrderDetailTable::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    return ret;
}

void OrderDetailTable::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getOrderDetailTableId())
        {
            binder << getValueOfOrderDetailTableId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getOrderMainTableId())
        {
            binder << getValueOfOrderMainTableId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getProductId())
        {
            binder << getValueOfProductId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getQuantityPurchased())
        {
            binder << getValueOfQuantityPurchased();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getPriceAtPurchase())
        {
            binder << getValueOfPriceAtPurchase();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value OrderDetailTable::toJson() const
{
    Json::Value ret;
    if(getOrderDetailTableId())
    {
        ret["order_detail_table_id"]=getValueOfOrderDetailTableId();
    }
    else
    {
        ret["order_detail_table_id"]=Json::Value();
    }
    if(getOrderMainTableId())
    {
        ret["order_main_table_id"]=getValueOfOrderMainTableId();
    }
    else
    {
        ret["order_main_table_id"]=Json::Value();
    }
    if(getProductId())
    {
        ret["product_id"]=getValueOfProductId();
    }
    else
    {
        ret["product_id"]=Json::Value();
    }
    if(getQuantityPurchased())
    {
        ret["quantity_purchased"]=getValueOfQuantityPurchased();
    }
    else
    {
        ret["quantity_purchased"]=Json::Value();
    }
    if(getPriceAtPurchase())
    {
        ret["price_at_purchase"]=getValueOfPriceAtPurchase();
    }
    else
    {
        ret["price_at_purchase"]=Json::Value();
    }
    return ret;
}

std::string OrderDetailTable::toString() const
{
    return toJson().toStyledString();
}

Json::Value OrderDetailTable::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 5)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getOrderDetailTableId())
            {
                ret[pMasqueradingVector[0]]=getValueOfOrderDetailTableId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getOrderMainTableId())
            {
                ret[pMasqueradingVector[1]]=getValueOfOrderMainTableId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getProductId())
            {
                ret[pMasqueradingVector[2]]=getValueOfProductId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getQuantityPurchased())
            {
                ret[pMasqueradingVector[3]]=getValueOfQuantityPurchased();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getPriceAtPurchase())
            {
                ret[pMasqueradingVector[4]]=getValueOfPriceAtPurchase();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getOrderDetailTableId())
    {
        ret["order_detail_table_id"]=getValueOfOrderDetailTableId();
    }
    else
    {
        ret["order_detail_table_id"]=Json::Value();
    }
    if(getOrderMainTableId())
    {
        ret["order_main_table_id"]=getValueOfOrderMainTableId();
    }
    else
    {
        ret["order_main_table_id"]=Json::Value();
    }
    if(getProductId())
    {
        ret["product_id"]=getValueOfProductId();
    }
    else
    {
        ret["product_id"]=Json::Value();
    }
    if(getQuantityPurchased())
    {
        ret["quantity_purchased"]=getValueOfQuantityPurchased();
    }
    else
    {
        ret["quantity_purchased"]=Json::Value();
    }
    if(getPriceAtPurchase())
    {
        ret["price_at_purchase"]=getValueOfPriceAtPurchase();
    }
    else
    {
        ret["price_at_purchase"]=Json::Value();
    }
    return ret;
}

bool OrderDetailTable::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("order_detail_table_id"))
    {
        if(!validJsonOfField(0, "order_detail_table_id", pJson["order_detail_table_id"], err, true))
            return false;
    }
    else
    {
        err="The order_detail_table_id column cannot be null";
        return false;
    }
    if(pJson.isMember("order_main_table_id"))
    {
        if(!validJsonOfField(1, "order_main_table_id", pJson["order_main_table_id"], err, true))
            return false;
    }
    else
    {
        err="The order_main_table_id column cannot be null";
        return false;
    }
    if(pJson.isMember("product_id"))
    {
        if(!validJsonOfField(2, "product_id", pJson["product_id"], err, true))
            return false;
    }
    else
    {
        err="The product_id column cannot be null";
        return false;
    }
    if(pJson.isMember("quantity_purchased"))
    {
        if(!validJsonOfField(3, "quantity_purchased", pJson["quantity_purchased"], err, true))
            return false;
    }
    else
    {
        err="The quantity_purchased column cannot be null";
        return false;
    }
    if(pJson.isMember("price_at_purchase"))
    {
        if(!validJsonOfField(4, "price_at_purchase", pJson["price_at_purchase"], err, true))
            return false;
    }
    else
    {
        err="The price_at_purchase column cannot be null";
        return false;
    }
    return true;
}
bool OrderDetailTable::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                          const std::vector<std::string> &pMasqueradingVector,
                                                          std::string &err)
{
    if(pMasqueradingVector.size() != 5)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool OrderDetailTable::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("order_detail_table_id"))
    {
        if(!validJsonOfField(0, "order_detail_table_id", pJson["order_detail_table_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("order_main_table_id"))
    {
        if(!validJsonOfField(1, "order_main_table_id", pJson["order_main_table_id"], err, false))
            return false;
    }
    if(pJson.isMember("product_id"))
    {
        if(!validJsonOfField(2, "product_id", pJson["product_id"], err, false))
            return false;
    }
    if(pJson.isMember("quantity_purchased"))
    {
        if(!validJsonOfField(3, "quantity_purchased", pJson["quantity_purchased"], err, false))
            return false;
    }
    if(pJson.isMember("price_at_purchase"))
    {
        if(!validJsonOfField(4, "price_at_purchase", pJson["price_at_purchase"], err, false))
            return false;
    }
    return true;
}
bool OrderDetailTable::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                        const std::vector<std::string> &pMasqueradingVector,
                                                        std::string &err)
{
    if(pMasqueradingVector.size() != 5)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool OrderDetailTable::validJsonOfField(size_t index,
                                        const std::string &fieldName,
                                        const Json::Value &pJson,
                                        std::string &err,
                                        bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
