/**
 *
 *  Product.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Product.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::testdb;

const std::string Product::Cols::_product_id = "product_id";
const std::string Product::Cols::_product_name = "product_name";
const std::string Product::Cols::_price = "price";
const std::string Product::Cols::_available_listing = "available_listing";
const std::string Product::Cols::_sales_volume = "sales_volume";
const std::string Product::primaryKeyName = "product_id";
const bool Product::hasPrimaryKey = true;
const std::string Product::tableName = "product";

const std::vector<typename Product::MetaData> Product::metaData_={
{"product_id","int32_t","int",4,0,1,1},
{"product_name","std::string","varchar(50)",50,0,0,1},
{"price","int32_t","int",4,0,0,1},
{"available_listing","int8_t","tinyint",1,0,0,1},
{"sales_volume","int32_t","int",4,0,0,1}
};
const std::string &Product::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Product::Product(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["product_id"].isNull())
        {
            productId_=std::make_shared<int32_t>(r["product_id"].as<int32_t>());
        }
        if(!r["product_name"].isNull())
        {
            productName_=std::make_shared<std::string>(r["product_name"].as<std::string>());
        }
        if(!r["price"].isNull())
        {
            price_=std::make_shared<int32_t>(r["price"].as<int32_t>());
        }
        if(!r["available_listing"].isNull())
        {
            availableListing_=std::make_shared<int8_t>(r["available_listing"].as<int8_t>());
        }
        if(!r["sales_volume"].isNull())
        {
            salesVolume_=std::make_shared<int32_t>(r["sales_volume"].as<int32_t>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 5 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            productId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            productName_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            price_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            availableListing_=std::make_shared<int8_t>(r[index].as<int8_t>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            salesVolume_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
    }

}

Product::Product(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 5)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            productId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            productName_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            price_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            availableListing_=std::make_shared<int8_t>((int8_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            salesVolume_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[4]].asInt64());
        }
    }
}

Product::Product(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("product_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["product_id"].isNull())
        {
            productId_=std::make_shared<int32_t>((int32_t)pJson["product_id"].asInt64());
        }
    }
    if(pJson.isMember("product_name"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["product_name"].isNull())
        {
            productName_=std::make_shared<std::string>(pJson["product_name"].asString());
        }
    }
    if(pJson.isMember("price"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["price"].isNull())
        {
            price_=std::make_shared<int32_t>((int32_t)pJson["price"].asInt64());
        }
    }
    if(pJson.isMember("available_listing"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["available_listing"].isNull())
        {
            availableListing_=std::make_shared<int8_t>((int8_t)pJson["available_listing"].asInt64());
        }
    }
    if(pJson.isMember("sales_volume"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["sales_volume"].isNull())
        {
            salesVolume_=std::make_shared<int32_t>((int32_t)pJson["sales_volume"].asInt64());
        }
    }
}

void Product::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 5)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            productId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            productName_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            price_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            availableListing_=std::make_shared<int8_t>((int8_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            salesVolume_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[4]].asInt64());
        }
    }
}

void Product::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("product_id"))
    {
        if(!pJson["product_id"].isNull())
        {
            productId_=std::make_shared<int32_t>((int32_t)pJson["product_id"].asInt64());
        }
    }
    if(pJson.isMember("product_name"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["product_name"].isNull())
        {
            productName_=std::make_shared<std::string>(pJson["product_name"].asString());
        }
    }
    if(pJson.isMember("price"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["price"].isNull())
        {
            price_=std::make_shared<int32_t>((int32_t)pJson["price"].asInt64());
        }
    }
    if(pJson.isMember("available_listing"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["available_listing"].isNull())
        {
            availableListing_=std::make_shared<int8_t>((int8_t)pJson["available_listing"].asInt64());
        }
    }
    if(pJson.isMember("sales_volume"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["sales_volume"].isNull())
        {
            salesVolume_=std::make_shared<int32_t>((int32_t)pJson["sales_volume"].asInt64());
        }
    }
}

const int32_t &Product::getValueOfProductId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(productId_)
        return *productId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Product::getProductId() const noexcept
{
    return productId_;
}
void Product::setProductId(const int32_t &pProductId) noexcept
{
    productId_ = std::make_shared<int32_t>(pProductId);
    dirtyFlag_[0] = true;
}
const typename Product::PrimaryKeyType & Product::getPrimaryKey() const
{
    assert(productId_);
    return *productId_;
}

const std::string &Product::getValueOfProductName() const noexcept
{
    static const std::string defaultValue = std::string();
    if(productName_)
        return *productName_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Product::getProductName() const noexcept
{
    return productName_;
}
void Product::setProductName(const std::string &pProductName) noexcept
{
    productName_ = std::make_shared<std::string>(pProductName);
    dirtyFlag_[1] = true;
}
void Product::setProductName(std::string &&pProductName) noexcept
{
    productName_ = std::make_shared<std::string>(std::move(pProductName));
    dirtyFlag_[1] = true;
}

const int32_t &Product::getValueOfPrice() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(price_)
        return *price_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Product::getPrice() const noexcept
{
    return price_;
}
void Product::setPrice(const int32_t &pPrice) noexcept
{
    price_ = std::make_shared<int32_t>(pPrice);
    dirtyFlag_[2] = true;
}

const int8_t &Product::getValueOfAvailableListing() const noexcept
{
    static const int8_t defaultValue = int8_t();
    if(availableListing_)
        return *availableListing_;
    return defaultValue;
}
const std::shared_ptr<int8_t> &Product::getAvailableListing() const noexcept
{
    return availableListing_;
}
void Product::setAvailableListing(const int8_t &pAvailableListing) noexcept
{
    availableListing_ = std::make_shared<int8_t>(pAvailableListing);
    dirtyFlag_[3] = true;
}

const int32_t &Product::getValueOfSalesVolume() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(salesVolume_)
        return *salesVolume_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Product::getSalesVolume() const noexcept
{
    return salesVolume_;
}
void Product::setSalesVolume(const int32_t &pSalesVolume) noexcept
{
    salesVolume_ = std::make_shared<int32_t>(pSalesVolume);
    dirtyFlag_[4] = true;
}

void Product::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Product::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "product_id",
        "product_name",
        "price",
        "available_listing",
        "sales_volume"
    };
    return inCols;
}

void Product::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getProductId())
        {
            binder << getValueOfProductId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getProductName())
        {
            binder << getValueOfProductName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getPrice())
        {
            binder << getValueOfPrice();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getAvailableListing())
        {
            binder << getValueOfAvailableListing();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getSalesVolume())
        {
            binder << getValueOfSalesVolume();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Product::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    return ret;
}

void Product::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getProductId())
        {
            binder << getValueOfProductId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getProductName())
        {
            binder << getValueOfProductName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getPrice())
        {
            binder << getValueOfPrice();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getAvailableListing())
        {
            binder << getValueOfAvailableListing();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getSalesVolume())
        {
            binder << getValueOfSalesVolume();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Product::toJson() const
{
    Json::Value ret;
    if(getProductId())
    {
        ret["product_id"]=getValueOfProductId();
    }
    else
    {
        ret["product_id"]=Json::Value();
    }
    if(getProductName())
    {
        ret["product_name"]=getValueOfProductName();
    }
    else
    {
        ret["product_name"]=Json::Value();
    }
    if(getPrice())
    {
        ret["price"]=getValueOfPrice();
    }
    else
    {
        ret["price"]=Json::Value();
    }
    if(getAvailableListing())
    {
        ret["available_listing"]=getValueOfAvailableListing();
    }
    else
    {
        ret["available_listing"]=Json::Value();
    }
    if(getSalesVolume())
    {
        ret["sales_volume"]=getValueOfSalesVolume();
    }
    else
    {
        ret["sales_volume"]=Json::Value();
    }
    return ret;
}

std::string Product::toString() const
{
    return toJson().toStyledString();
}

Json::Value Product::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 5)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getProductId())
            {
                ret[pMasqueradingVector[0]]=getValueOfProductId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getProductName())
            {
                ret[pMasqueradingVector[1]]=getValueOfProductName();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getPrice())
            {
                ret[pMasqueradingVector[2]]=getValueOfPrice();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getAvailableListing())
            {
                ret[pMasqueradingVector[3]]=getValueOfAvailableListing();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getSalesVolume())
            {
                ret[pMasqueradingVector[4]]=getValueOfSalesVolume();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getProductId())
    {
        ret["product_id"]=getValueOfProductId();
    }
    else
    {
        ret["product_id"]=Json::Value();
    }
    if(getProductName())
    {
        ret["product_name"]=getValueOfProductName();
    }
    else
    {
        ret["product_name"]=Json::Value();
    }
    if(getPrice())
    {
        ret["price"]=getValueOfPrice();
    }
    else
    {
        ret["price"]=Json::Value();
    }
    if(getAvailableListing())
    {
        ret["available_listing"]=getValueOfAvailableListing();
    }
    else
    {
        ret["available_listing"]=Json::Value();
    }
    if(getSalesVolume())
    {
        ret["sales_volume"]=getValueOfSalesVolume();
    }
    else
    {
        ret["sales_volume"]=Json::Value();
    }
    return ret;
}

bool Product::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("product_id"))
    {
        if(!validJsonOfField(0, "product_id", pJson["product_id"], err, true))
            return false;
    }
    else
    {
        err="The product_id column cannot be null";
        return false;
    }
    if(pJson.isMember("product_name"))
    {
        if(!validJsonOfField(1, "product_name", pJson["product_name"], err, true))
            return false;
    }
    else
    {
        err="The product_name column cannot be null";
        return false;
    }
    if(pJson.isMember("price"))
    {
        if(!validJsonOfField(2, "price", pJson["price"], err, true))
            return false;
    }
    else
    {
        err="The price column cannot be null";
        return false;
    }
    if(pJson.isMember("available_listing"))
    {
        if(!validJsonOfField(3, "available_listing", pJson["available_listing"], err, true))
            return false;
    }
    else
    {
        err="The available_listing column cannot be null";
        return false;
    }
    if(pJson.isMember("sales_volume"))
    {
        if(!validJsonOfField(4, "sales_volume", pJson["sales_volume"], err, true))
            return false;
    }
    else
    {
        err="The sales_volume column cannot be null";
        return false;
    }
    return true;
}
bool Product::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                 const std::vector<std::string> &pMasqueradingVector,
                                                 std::string &err)
{
    if(pMasqueradingVector.size() != 5)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Product::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("product_id"))
    {
        if(!validJsonOfField(0, "product_id", pJson["product_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("product_name"))
    {
        if(!validJsonOfField(1, "product_name", pJson["product_name"], err, false))
            return false;
    }
    if(pJson.isMember("price"))
    {
        if(!validJsonOfField(2, "price", pJson["price"], err, false))
            return false;
    }
    if(pJson.isMember("available_listing"))
    {
        if(!validJsonOfField(3, "available_listing", pJson["available_listing"], err, false))
            return false;
    }
    if(pJson.isMember("sales_volume"))
    {
        if(!validJsonOfField(4, "sales_volume", pJson["sales_volume"], err, false))
            return false;
    }
    return true;
}
bool Product::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                               const std::vector<std::string> &pMasqueradingVector,
                                               std::string &err)
{
    if(pMasqueradingVector.size() != 5)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Product::validJsonOfField(size_t index,
                               const std::string &fieldName,
                               const Json::Value &pJson,
                               std::string &err,
                               bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 50)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 50)";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
